site_name: Brilliance Admin

plugins:
    - search
    - macros

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.inlinehilite

repo_url: https://github.com/brilliance-admin/backend-python
repo_name: brilliance-admin/backend-python

theme:
  name: material
  favicon: assets/favicon.jpg


  features:
    - content.code.copy
    - content.code.annotate
    - navigation.expand

  font:
    text: Roboto
    code: Roboto Mono

  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode


extra:
    demo_url: https://brilliance-admin.com

nav:
  - Overview: index.md
  - How to start: how-to-start.md
  - Authentication: authentication.md
  - Translations: translations.md
  - Admin Schema:
      - Main/Group/Category: admin-schema/main.md
      - Tables: admin-schema/tables.md
      - Graphs: admin-schema/graphs.md
  - Integrations:
      - SQLAlchemy: integration/sqlalchemy/index.md
