[project]
name = "backend-python-docs"
version = "0.1.0"
description = "Backend python docs"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-macros-plugin>=1.3.7",
    "mkdocs-material>=9.6.3",
    "pymdown-extensions>=10.20",
]
